= My Project
Daryan Mamsaleh, Leon Marazovic, Deniz Becer, Marko Trkulja, Ernad Music
1.0.0, {docdate}: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/asciidoctor-docker-template] ‏ ‏ ‎
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Pflichtenheft "Was mache ich"


=== Ausgangssituation

DnD ist ein Pen-and-Paper-Spiel, bei dem man ein Roleplay-Abenteuer erlebt, wobei die Möglichkeiten sehr vielseitig und beinahe grenzenlos sind. Es bietet eine große Vielfalt bei der Charaktererstellung, zum Beispiel in Bezug auf Klassen, Völker, Hintergründe usw.

=== Istzustand
Aktuell kann man diese Charaktere manuell in Form von Stift und Papier verfassen oder online einen Charakter erstellen, mit verschiedensten Fähigkeiten und Eigenschaften. Dabei muss man für die Erstellung selbst viel recherchieren, welche Klassen oder Völker welche Eigenschaften haben.

=== Problemstellung
=== Aufgabenstellung
==== Funktionale Anforderungen

[plantuml,wireframe,png]
----
@startsalt
{
Name         | "                 "
Modifiers:   | { (X) public | () default | () private | () protected
	            [] abstract | [] final   | [] static }
Superclass:  | { "java.lang.Object " | [Browse...] }
}
@endsalt
----
==== Nichtfunktionale Anforderungen (NFA)
=== Ziele
Die Ziele des Projekts sind, die Charaktererstellung für den Benutzer zu vereinfachen und übersichtlich zu gestalten. Durch eine geführte Erstellung ist kaum Vorwissen erforderlich. Die strukturierte Darstellung ermöglicht eine schnelle Charaktererstellung und reduziert sowohl den Zeit- als auch den Rechercheaufwand im Vergleich zur manuellen Erstellung mit Stift und Papier.

=== Mengengerüst
=== Rahmenbedingungen
Das Projekt wird als Gruppenarbeit von fünf Personen im Rahmen des Schuljahres durchgeführt. Die Umsetzung erfolgt in Java unter Verwendung von JavaFX für die Benutzeroberfläche.

== Entwurf "Wie mache ich es"
=== Systemarchitektur
=== ...

== Projekthandbuch "Organisatorische Rahmenbedingungen"



=== GANTT-Diagramm

mit User-Stories (definiert in YouTrack)

[plantuml,gantt-protoype,png]
----
@startgantt
[Test prototype] lasts 10 days
[Prototype completed] happens at [Test prototype]'s end
[Setup assembly line] lasts 12 days
[Setup assembly line] starts at [Test prototype]'s end
[Test prototype 2] lasts 3 days
[Test prototype 2] starts at [Prototype completed]'s end
@endgantt
----



* link:minutes-of-meeting.html[Protokollvorlage]
* link:demo.html[Demo]

